### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by grantboxer** [jvdkwast/qgis-processing-pcraster#59]
I have installed pcraster plugin via the plugin and then used the OSGeo4W network installer.

I keep getting this error on QGIS start-up. Any suggestions?

Grant Boxer

2023-10-08T11:55:11     CRITICAL    Traceback (most recent call last):
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 448, in startPlugin
              plugins[packageName].initGui()
              File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pcraster_tools\pcraster_plugin.py", line 104, in initGui
              import pcraster # pylint: disable=import-outside-toplevel,unused-import
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pcraster\__init__.py", line 17, in 
              os.add_dll_directory(pcraster_bin_pathname)
              File "C:\OSGeo4W\apps\Python39\lib\os.py", line 1111, in add_dll_directory
              cookie = nt._add_dll_directory(path)
             OSError: [WinError 87] The parameter is incorrect: '.'

**Comment by cucubalus** [comment]
Hello together -I think I have nearly the same problem and get the following error message: 

Couldn't load plugin 'pcraster_tools' due to an error when calling its initGui() method 
OSError: [WinError 87] Falscher Parameter: '.' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/Lutz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pcraster_tools\pcraster_plugin.py", line 104, in initGui
    import pcraster  # pylint: disable=import-outside-toplevel,unused-import
  File "C:\PROGRA~1/QGIS32~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS32~1.11\apps\Python39\lib\site-packages\pcraster\__init__.py", line 17, in 
    os.add_dll_directory(pcraster_bin_pathname)
  File "C:\PROGRA~1\QGIS32~1.11\apps\Python39\lib\os.py", line 1111, in add_dll_directory
    cookie = nt._add_dll_directory(path)
OSError: [WinError 87] Falscher Parameter: '.'
Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.12-Firenze Firenze, dcc633b2de 

Does anyone have any ideas on this ??

**Comment by OliverSchmitz** [comment]
The import of the PCRaster module on Windows is tested and works for Python 3.8-3.12 for our Conda installation. `pcraster_init.py` is not part of our package, do you have an idea where that is coming from? Guessing from the error message it could be a renamed and moved version of our `__init__.py`?

**Comment by FredericFournier** [comment]
Hi, I have the same problem than cucubalus when I try to activate the PCRaster plugin.

I use QGIS 3.34.1 and Python version 3.9.5

**Comment by jvdkwast** [comment]
Any idea what goes wrong here, @nyalldawson ?

**Comment by nyalldawson** [comment]
It must be an osgeo4w packaging issue -- @jef-n any insights?

**Comment by jef-n** [comment]
pcraster_init.py is not part of the osgeo4w package either.

**Comment by cucubalus** [comment]
since the failed PCRaster installation I get the enclosed error message - even after uninstalling PCRaster - maybe this will help to find the cause ?

![QGIS_error_message](https://github.com/jvdkwast/qgis-processing-pcraster/assets/90332634/8d99c386-5eef-4068-b151-d544be11243a)

**Comment by jef-n** [comment]
hm, so you're running qgis in OSGeo4W's bin directory (the shortcut should run it from your Documents directory), so pcraster finds "pcrcalc.exe" in the current directory ie. "." and in turn it tries to add that to the dll search path, which apparently doesn't work (IIRC "." is included anyway - plus OSGeo4W's bin is also already included in our case).   I'd say that's a bug in pcraster. 

```
# Python Console
# Use iface to access QGIS API interface or type '?' for more info
# Security warning: typing commands from an untrusted source can harm your computer
>>> os.getcwd()
'C:\\OSGeo4W\\bin'
>>> from shutil import which
>>> which("pcrcalc.exe")
'.\\pcrcalc.exe'
>>> sys.platform
'win32'
>>> import pcraster
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\pcraster\__init__.py", line 17, in <module>
    os.add_dll_directory(pcraster_bin_pathname)
  File "C:\OSGeo4W\apps\Python39\lib\os.py", line 1111, in add_dll_directory
    cookie = nt._add_dll_directory(path)
OSError: [WinError 87] Falscher Parameter: '.'
>>> os.chdir("/")
import pcraster
>>> 
```
